# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proto/coordinate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/proto/coordinate.proto',
  package='wheresbrendan',
  serialized_pb=_b('\n\x1a\x61pp/proto/coordinate.proto\x12\rwheresbrendan\"1\n\nCoordinate\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COORDINATE = _descriptor.Descriptor(
  name='Coordinate',
  full_name='wheresbrendan.Coordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='wheresbrendan.Coordinate.latitude', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='wheresbrendan.Coordinate.longitude', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['Coordinate'] = _COORDINATE

Coordinate = _reflection.GeneratedProtocolMessageType('Coordinate', (_message.Message,), dict(
  DESCRIPTOR = _COORDINATE,
  __module__ = 'app.proto.coordinate_pb2'
  # @@protoc_insertion_point(class_scope:wheresbrendan.Coordinate)
  ))
_sym_db.RegisterMessage(Coordinate)


# @@protoc_insertion_point(module_scope)
