# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proto/stop.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import app.proto.coordinate_pb2
import app.proto.duration_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/proto/stop.proto',
  package='wheresbrendan',
  serialized_pb=_b('\n\x14\x61pp/proto/stop.proto\x12\rwheresbrendan\x1a\x1a\x61pp/proto/coordinate.proto\x1a\x18\x61pp/proto/duration.proto\"x\n\x04Stop\x12\n\n\x02id\x18\x01 \x01(\t\x12+\n\x08location\x18\x02 \x01(\x0b\x32\x19.wheresbrendan.Coordinate\x12\"\n\x05stays\x18\x03 \x03(\x0b\x32\x13.wheresbrendan.Stay\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"f\n\x04Stay\x12\n\n\x02id\x18\x01 \x01(\t\x12)\n\x08\x64uration\x18\x02 \x01(\x0b\x32\x17.wheresbrendan.Duration\x12\x12\n\nshort_stay\x18\x03 \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t')
  ,
  dependencies=[app.proto.coordinate_pb2.DESCRIPTOR,app.proto.duration_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STOP = _descriptor.Descriptor(
  name='Stop',
  full_name='wheresbrendan.Stop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='wheresbrendan.Stop.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='wheresbrendan.Stop.location', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stays', full_name='wheresbrendan.Stop.stays', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='wheresbrendan.Stop.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=213,
)


_STAY = _descriptor.Descriptor(
  name='Stay',
  full_name='wheresbrendan.Stay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='wheresbrendan.Stay.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='wheresbrendan.Stay.duration', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='short_stay', full_name='wheresbrendan.Stay.short_stay', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='wheresbrendan.Stay.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=317,
)

_STOP.fields_by_name['location'].message_type = app.proto.coordinate_pb2._COORDINATE
_STOP.fields_by_name['stays'].message_type = _STAY
_STAY.fields_by_name['duration'].message_type = app.proto.duration_pb2._DURATION
DESCRIPTOR.message_types_by_name['Stop'] = _STOP
DESCRIPTOR.message_types_by_name['Stay'] = _STAY

Stop = _reflection.GeneratedProtocolMessageType('Stop', (_message.Message,), dict(
  DESCRIPTOR = _STOP,
  __module__ = 'app.proto.stop_pb2'
  # @@protoc_insertion_point(class_scope:wheresbrendan.Stop)
  ))
_sym_db.RegisterMessage(Stop)

Stay = _reflection.GeneratedProtocolMessageType('Stay', (_message.Message,), dict(
  DESCRIPTOR = _STAY,
  __module__ = 'app.proto.stop_pb2'
  # @@protoc_insertion_point(class_scope:wheresbrendan.Stay)
  ))
_sym_db.RegisterMessage(Stay)


# @@protoc_insertion_point(module_scope)
